-- DROP FUNCTION calc_revenue1_f1;
DELIMITER $$

CREATE FUNCTION CALC_REVENUE_F1 (QUANTITY INTEGER,VEHICLE_PRICE DECIMAL(14,2), DISCOUNT DECIMAL(4,2))
RETURNS INTEGER
DETERMINISTIC
BEGIN
	DECLARE REVENUE INTEGER;
    SET REVENUE = QUANTITY * (VEHICLE_PRICE - (VEHICLE_PRICE * (DISCOUNT / 100)));
    RETURN REVENUE;
END;

-- for revenues by order
SELECT ORDER_ID, QUANTITY, VEHICLE_PRICE, DISCOUNT, CALC_REVENUE_F(QUANTITY,VEHICLE_PRICE, DISCOUNT) AS REVENUE
FROM vehicles_t
order by 5 desc ;

- for revenues by quarter
SELECT
	QUARTER_NUMBER,
    SUM(CALC_REVENUE_F1(QUANTITY, VEHICLE_PRICE, DISCOUNT)) AS REVENUE
FROM VEHICLES_T
GROUP BY QUARTER_NUMBER
ORDER BY QUARTER_NUMBER DESC;

-- single sum revenue result for all contained quaters in main table
SELECT
    SUM(CALC_REVENUE_F1(QUANTITY,VEHICLE_PRICE, DISCOUNT)) REVENUE
FROM VEHICLES_T;