DELIMITER $$
CREATE PROCEDURE customer_p()
BEGIN
    INSERT INTO customer_t (
   		CUSTOMER_ID, 
		CUSTOMER_NAME, 
		GENDER, 
		JOB_TITLE, 
		PHONE_NUMBER, 
		EMAIL_ADDRESS, 
		CITY,
		COUNTRY,
		STATE,
		CUSTOMER_ADDRESS, 
		CREDIT_CARD_TYPE, 
		CREDIT_CARD_NUMBER
	) 
    SELECT DISTINCT 
		CUSTOMER_ID, 
		CUSTOMER_NAME, 
		GENDER, 
		JOB_TITLE, 
		PHONE_NUMBER, 
		EMAIL_ADDRESS, 
		CITY,
		COUNTRY,
		STATE,
		CUSTOMER_ADDRESS, 
		CREDIT_CARD_TYPE, 
		CREDIT_CARD_NUMBER
	
	FROM vehicles_t WHERE CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM customer_t);
END;

-- select count(distinct customer_id) from customer_t;
-- CALL customer_p();
-- FROM vehdb1.vehicles_t WHERE QUARTER_NUMBER = quarter_num;
-- WHERE CUSTOMER_ID NOT IN (SELECT DISTINCT CUSTOMER_ID FROM customer_t)