DELIMITER $$ 
CREATE PROCEDURE order_p(quarter_num INTEGER)
BEGIN
	INSERT INTO vehdb1.order_t (
		ORDER_ID, 
		CUSTOMER_ID,
		SHIPPER_ID,
		PRODUCT_ID,
		QUANTITY,
		VEHICLE_PRICE,
		ORDER_DATE, 
		SHIP_DATE,
		DISCOUNT,
		SHIP_MODE,
		SHIPPING,  
		CUSTOMER_FEEDBACK,
		QUARTER_NUMBER 
	) 
SELECT DISTINCT
		ORDER_ID, 
		CUSTOMER_ID,
		SHIPPER_ID,
		PRODUCT_ID,
		QUANTITY,
		VEHICLE_PRICE,
		ORDER_DATE, 
		SHIP_DATE,
		DISCOUNT,
		SHIP_MODE,
		SHIPPING,  
		CUSTOMER_FEEDBACK,
		QUARTER_NUMBER 
FROM vehdb1.vehicles_t WHERE QUARTER_NUMBER = quarter_num;
END;

-- CALL order_p(4);
