CREATE VIEW veh_prod_cust_v AS
   SELECT
	CUS.CUSTOMER_ID,
	CUS.CUSTOMER_NAME,
 	CUS.CREDIT_CARD_TYPE,
	CUS.STATE,
	ORD.ORDER_ID,
	ORD.CUSTOMER_FEEDBACK,
    	PRO.PRODUCT_ID,
    	PRO.VEHICLE_MAKER,
    	PRO.VEHICLE_MODEL,
	PRO.VEHICLE_COLOR,
    	PRO.VEHICLE_MODEL_YEAR

   FROM customer_t cus
   JOIN
	order_t ord
   USING (CUSTOMER_ID) 
   JOIN
	product_t pro
   USING (PRODUCT_ID)
   GROUP BY CUSTOMER_NAME;

