 CREATE VIEW veh_ord_cust_v AS
    SELECT 
	CUS.CUSTOMER_ID,
	CUS.CUSTOMER_NAME,
   	CUS.CITY,
	CUS.STATE,
	CUS.CREDIT_CARD_TYPE,
	ORD.ORDER_ID,
	ORD.SHIPPER_ID,
	ORD.PRODUCT_ID,
	ORD.QUANTITY,
	ORD.VEHICLE_PRICE,
	ORD.ORDER_DATE,
	ORD.SHIP_DATE,
	ORD.DISCOUNT,
	ORD.CUSTOMER_FEEDBACK,
	ORD.QUARTER_NUMBER


    FROM customer_t CUS
    INNER JOIN order_t ORD
    
    ON CUS.CUSTOMER_ID=ORD.CUSTOMER_ID
    GROUP BY CUSTOMER_NAME;
